name: Build/release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run make

      - name: Publish artifacts on ubuntu
        uses: actions/upload-artifact@v2
        with:
          name: xbox-xcloud-electron-linux.zip
          path: |
            out/*.deb
            out/*.rpm
        if: matrix.os == 'ubuntu-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

      - name: Publish artifacts on osx
        uses: actions/upload-artifact@v2
        with:
          name: xbox-xcloud-electron-osx.zip
          path: |
            out/*.app
        if: matrix.os == 'macos-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

      - name: Publish artifacts on windows
        uses: actions/upload-artifact@v2
        with:
          name: xbox-xcloud-electron-windows.zip
          path: |
            out/*.exe
        if: matrix.os == 'windows-latest' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))